export const ActionTypes = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCTS_BY_ID: "GET_PRODUCTS_BY_ID",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  FAILED_GET_PRODUCTS: "FAILED_GET_PRODUCTS",
};
