export const ActionTypes = {
  //Users
  LOGIN_USER: "LOGIN_USER",
  GET_USER: "GET_USER",
  GET_USER_BY_ID: "GET_USER_BY_ID",
  UPDATE_USER: "UPDATE_USER",
  REMOVE_USER: "REMOVE_USER",
  FAILED_USER: "FAILED_USER",

  //Products
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCTS_BY_ID: "GET_PRODUCTS_BY_ID",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  FAILED_GET_PRODUCTS: "FAILED_GET_PRODUCTS",

  //Orders
  GET_Order: "GET_Order",
  GET_ORDER_BY_ID: "GET_ORDER_BY_ID",
  UPDATE_ORDER: "UPDATE_ORDER",
  REMOVE_ORDER: "REMOVE_ORDER",
  FAILED_Order: "FAILED_Order",
};
